WhoCanDo.Database.Enchanting = {
    [7418] = {name = "enchant bracer minor health"},
    [7420] = {name = "enchant chest minor health"},
    [7421] = {name = "runed copper rod"},
    [7426] = {name = "enchant chest minor absorption"},
    [7428] = {name = "enchant bracer minor deflection"},
    [7443] = {name = "enchant chest minor mana"},
    [7454] = {name = "enchant cloak minor resistance"},
    [7457] = {name = "enchant bracer minor stamina"},
    [7745] = {name = "enchant 2h weapon minor impact"},
    [7748] = {name = "enchant chest lesser health"},
    [7766] = {name = "enchant bracer minor spirit"},
    [7771] = {name = "enchant cloak minor protection"},
    [7776] = {name = "enchant chest lesser mana"},
    [7779] = {name = "enchant bracer minor agility"},
    [7782] = {name = "enchant bracer minor strength"},
    [7786] = {name = "enchant weapon minor beastslayer"},
    [7788] = {name = "enchant weapon minor striking"},
    [7793] = {name = "enchant 2h weapon lesser intellect"},
    [7795] = {name = "runed silver rod"},
    [7857] = {name = "enchant chest health"},
    [7859] = {name = "enchant bracer lesser spirit"},
    [7861] = {name = "enchant cloak lesser fire resistance"},
    [7863] = {name = "enchant boots minor stamina"},
    [7867] = {name = "enchant boots minor agility"},
    [13262] = {name = "disenchant"},
    [13378] = {name = "enchant shield minor stamina"},
    [13380] = {name = "enchant 2h weapon lesser spirit"},
    [13419] = {name = "enchant cloak minor agility"},
    [13421] = {name = "enchant cloak lesser protection"},
    [13464] = {name = "enchant shield lesser protection"},
    [13485] = {name = "enchant shield lesser spirit"},
    [13501] = {name = "enchant bracer lesser stamina"},
    [13503] = {name = "enchant weapon lesser striking"},
    [13522] = {name = "enchant cloak lesser shadow resistance"},
    [13529] = {name = "enchant 2h weapon lesser impact"},
    [13536] = {name = "enchant bracer lesser strength"},
    [13538] = {name = "enchant chest lesser absorption"},
    [13607] = {name = "enchant chest mana"},
    [13612] = {name = "enchant gloves mining"},
    [13617] = {name = "enchant gloves herbalism"},
    [13620] = {name = "enchant gloves fishing"},
    [13622] = {name = "enchant bracer lesser intellect"},
    [13626] = {name = "enchant chest minor stats"},
    [13628] = {name = "runed golden rod"},
    [13631] = {name = "enchant shield lesser stamina"},
    [13635] = {name = "enchant cloak defense"},
    [13637] = {name = "enchant boots lesser agility"},
    [13640] = {name = "enchant chest greater health"},
    [13642] = {name = "enchant bracer spirit"},
    [13644] = {name = "enchant boots lesser stamina"},
    [13646] = {name = "enchant bracer lesser deflection"},
    [13648] = {name = "enchant bracer stamina"},
    [13653] = {name = "enchant weapon lesser beastslayer"},
    [13655] = {name = "enchant weapon lesser elemental slayer"},
    [13657] = {name = "enchant cloak fire resistance"},
    [13659] = {name = "enchant shield spirit"},
    [13661] = {name = "enchant bracer strength"},
    [13663] = {name = "enchant chest greater mana"},
    [13687] = {name = "enchant boots lesser spirit"},
    [13689] = {name = "enchant shield lesser block"},
    [13693] = {name = "enchant weapon striking"},
    [13695] = {name = "enchant 2h weapon impact"},
    [13698] = {name = "enchant gloves skinning"},
    [13700] = {name = "enchant chest lesser stats"},
    [13702] = {name = "runed truesilver rod"},
    [13746] = {name = "enchant cloak greater defense"},
    [13794] = {name = "enchant cloak resistance"},
    [13815] = {name = "enchant gloves agility"},
    [13817] = {name = "enchant shield stamina"},
    [13822] = {name = "enchant bracer intellect"},
    [13836] = {name = "enchant boots stamina"},
    [13841] = {name = "enchant gloves advanced mining"},
    [13846] = {name = "enchant bracer greater spirit"},
    [13858] = {name = "enchant chest superior health"},
    [13868] = {name = "enchant gloves advanced herbalism"},
    [13882] = {name = "enchant cloak lesser agility"},
    [13887] = {name = "enchant gloves strength"},
    [13890] = {name = "enchant boots minor speed"},
    [13898] = {name = "enchant weapon fiery weapon"},
    [13905] = {name = "enchant shield greater spirit"},
    [13915] = {name = "enchant weapon demonslaying"},
    [13917] = {name = "enchant chest superior mana"},
    [13931] = {name = "enchant bracer deflection"},
    [13933] = {name = "enchant shield frost resistance"},
    [13935] = {name = "enchant boots agility"},
    [13937] = {name = "enchant 2h weapon greater impact"},
    [13939] = {name = "enchant bracer greater strength"},
    [13941] = {name = "enchant chest stats"},
    [13943] = {name = "enchant weapon greater striking"},
    [13945] = {name = "enchant bracer greater stamina"},
    [13947] = {name = "enchant gloves riding skill"},
    [13948] = {name = "enchant gloves minor haste"},
    [14293] = {name = "lesser magic wand"},
    [14807] = {name = "greater magic wand"},
    [14809] = {name = "lesser mystic wand"},
    [14810] = {name = "greater mystic wand"},
    [15596] = {name = "smoking heart of the mountain"},
    [17180] = {name = "enchanted thorium"},
    [17181] = {name = "enchanted leather"},
    [20008] = {name = "enchant bracer greater intellect"},
    [20009] = {name = "enchant bracer superior spirit"},
    [20010] = {name = "enchant bracer superior strength"},
    [20011] = {name = "enchant bracer superior stamina"},
    [20012] = {name = "enchant gloves greater agility"},
    [20013] = {name = "enchant gloves greater strength"},
    [20014] = {name = "enchant cloak greater resistance"},
    [20015] = {name = "enchant cloak superior defense"},
    [20016] = {name = "enchant shield vitality"},
    [20017] = {name = "enchant shield greater stamina"},
    [20020] = {name = "enchant boots greater stamina"},
    [20023] = {name = "enchant boots greater agility"},
    [20024] = {name = "enchant boots spirit"},
    [20025] = {name = "enchant chest greater stats"},
    [20026] = {name = "enchant chest major health"},
    [20028] = {name = "enchant chest major mana"},
    [20029] = {name = "enchant weapon icy chill"},
    [20030] = {name = "enchant 2h weapon superior impact"},
    [20031] = {name = "enchant weapon superior striking"},
    [20032] = {name = "enchant weapon lifestealing"},
    [20033] = {name = "enchant weapon unholy weapon"},
    [20034] = {name = "enchant weapon crusader"},
    [20035] = {name = "enchant 2h weapon major spirit"},
    [20036] = {name = "enchant 2h weapon major intellect"},
    [20051] = {name = "runed arcanite rod"},
    [21931] = {name = "enchant weapon winter's might"},
    [22749] = {name = "enchant weapon spellpower"},
    [22750] = {name = "enchant weapon healing power"},
    [23799] = {name = "enchant weapon strength"},
    [23800] = {name = "enchant weapon agility"},
    [23801] = {name = "enchant bracer mana regeneration"},
    [23802] = {name = "enchant bracer healing power"},
    [23803] = {name = "enchant weapon mighty spirit"},
    [23804] = {name = "enchant weapon mighty intellect"},
    [25072] = {name = "enchant gloves threat"},
    [25073] = {name = "enchant gloves shadow power"},
    [25074] = {name = "enchant gloves frost power"},
    [25078] = {name = "enchant gloves fire power"},
    [25079] = {name = "enchant gloves healing power"},
    [25080] = {name = "enchant gloves superior agility"},
    [25081] = {name = "enchant cloak greater fire resistance"},
    [25082] = {name = "enchant cloak greater nature resistance"},
    [25083] = {name = "enchant cloak stealth"},
    [25084] = {name = "enchant cloak subtlety"},
    [25086] = {name = "enchant cloak dodge"},
    [25124] = {name = "minor wizard oil"},
    [25125] = {name = "minor mana oil"},
    [25126] = {name = "lesser wizard oil"},
    [25127] = {name = "lesser mana oil"},
    [25128] = {name = "wizard oil"},
    [25129] = {name = "brilliant wizard oil"},
    [25130] = {name = "brilliant mana oil"},
    [27837] = {name = "enchant 2h weapon agility"},
    [27899] = {name = "enchant bracer brawn"},
    [27905] = {name = "enchant bracer stats"},
    [27906] = {name = "enchant bracer major defense"},
    [27911] = {name = "enchant bracer superior healing"},
    [27913] = {name = "enchant bracer restore mana prime"},
    [27914] = {name = "enchant bracer fortitude"},
    [27917] = {name = "enchant bracer spellpower"},
    [27920] = {name = "enchant ring striking"},
    [27924] = {name = "enchant ring spellpower"},
    [27926] = {name = "enchant ring healing power"},
    [27927] = {name = "enchant ring stats"},
    [27944] = {name = "enchant shield tough shield"},
    [27945] = {name = "enchant shield intellect"},
    [27946] = {name = "enchant shield shield block"},
    [27947] = {name = "enchant shield resistance"},
    [27948] = {name = "enchant boots vitality"},
    [27950] = {name = "enchant boots fortitude"},
    [27951] = {name = "enchant boots dexterity"},
    [27954] = {name = "enchant boots surefooted"},
    [27957] = {name = "enchant chest exceptional health"},
    [27958] = {name = "enchant chest exceptional mana"},
    [27960] = {name = "enchant chest exceptional stats"},
    [27961] = {name = "enchant cloak major armor"},
    [27962] = {name = "enchant cloak major resistance"},
    [27967] = {name = "enchant weapon major striking"},
    [27968] = {name = "enchant weapon major intellect"},
    [27971] = {name = "enchant 2h weapon savagery"},
    [27972] = {name = "enchant weapon potency"},
    [27975] = {name = "enchant weapon major spellpower"},
    [27977] = {name = "enchant 2h weapon major agility"},
    [27981] = {name = "enchant weapon sunfire"},
    [27982] = {name = "enchant weapon soulfrost"},
    [27984] = {name = "enchant weapon mongoose"},
    [28003] = {name = "enchant weapon spellsurge"},
    [28004] = {name = "enchant weapon battlemaster"},
    [28016] = {name = "superior mana oil"},
    [28019] = {name = "superior wizard oil"},
    [28022] = {name = "large prismatic shard"},
    [28027] = {name = "prismatic sphere"},
    [28028] = {name = "void sphere"},
    [32664] = {name = "runed fel iron rod"},
    [32665] = {name = "runed adamantite rod"},
    [32667] = {name = "runed eternium rod"},
    [33990] = {name = "enchant chest major spirit"},
    [33991] = {name = "enchant chest restore mana prime"},
    [33992] = {name = "enchant chest major resilience"},
    [33993] = {name = "enchant gloves blasting"},
    [33994] = {name = "enchant gloves precise strikes"},
    [33995] = {name = "enchant gloves major strength"},
    [33996] = {name = "enchant gloves assault"},
    [33997] = {name = "enchant gloves major spellpower"},
    [33999] = {name = "enchant gloves major healing"},
    [34001] = {name = "enchant bracer major intellect"},
    [34002] = {name = "enchant bracer assault"},
    [34003] = {name = "enchant cloak spell penetration"},
    [34004] = {name = "enchant cloak greater agility"},
    [34005] = {name = "enchant cloak greater arcane resistance"},
    [34006] = {name = "enchant cloak greater shadow resistance"},
    [34007] = {name = "enchant boots cat's swiftness"},
    [34008] = {name = "enchant boots boar's speed"},
    [34009] = {name = "enchant shield major stamina"},
    [34010] = {name = "enchant weapon major healing"},
    [42613] = {name = "nexus transformation"},
    [42615] = {name = "small prismatic shard"},
    [42620] = {name = "enchant weapon greater agility"},
    [42974] = {name = "enchant weapon executioner"},
    [44383] = {name = "enchant shield resilience"},
    [44483] = {name = "enchant cloak superior frost resistance"},
    [44484] = {name = "enchant gloves expertise"},
    [44488] = {name = "enchant gloves precision"},
    [44489] = {name = "enchant shield defense"},
    [44492] = {name = "enchant chest mighty health"},
    [44494] = {name = "enchant cloak superior nature resistance"},
    [44500] = {name = "enchant cloak superior agility"},
    [44506] = {name = "enchant gloves gatherer"},
    [44508] = {name = "enchant boots greater spirit"},
    [44509] = {name = "enchant chest greater mana restoration"},
    [44510] = {name = "enchant weapon exceptional spirit"},
    [44513] = {name = "enchant gloves greater assault"},
    [44524] = {name = "enchant weapon icebreaker"},
    [44528] = {name = "enchant boots greater fortitude"},
    [44529] = {name = "enchant gloves major agility"},
    [44555] = {name = "enchant bracers exceptional intellect"},
    [44556] = {name = "enchant cloak superior fire resistance"},
    [44575] = {name = "enchant bracers greater assault"},
    [44576] = {name = "enchant weapon lifeward"},
    [44582] = {name = "enchant cloak spell piercing"},
    [44584] = {name = "enchant boots greater vitality"},
    [44588] = {name = "enchant chest exceptional resilience"},
    [44589] = {name = "enchant boots superior agility"},
    [44590] = {name = "enchant cloak superior shadow resistance"},
    [44591] = {name = "enchant cloak titanweave"},
    [44592] = {name = "enchant gloves exceptional spellpower"},
    [44593] = {name = "enchant bracers major spirit"},
    [44595] = {name = "enchant 2h weapon scourgebane"},
    [44596] = {name = "enchant cloak superior arcane resistance"},
    [44598] = {name = "enchant bracers expertise"},
    [44616] = {name = "enchant bracers greater stats"},
    [44621] = {name = "enchant weapon giant slayer"},
    [44623] = {name = "enchant chest super stats"},
    [44625] = {name = "enchant gloves armsman"},
    [44629] = {name = "enchant weapon exceptional spellpower"},
    [44630] = {name = "enchant 2h weapon greater savagery"},
    [44631] = {name = "enchant cloak shadow armor"},
    [44633] = {name = "enchant weapon exceptional agility"},
    [44635] = {name = "enchant bracers greater spellpower"},
    [44636] = {name = "enchant ring greater spellpower"},
    [44645] = {name = "enchant ring assault"},
    [45765] = {name = "void shatter"},
    [46578] = {name = "enchant weapon deathfrost"},
    [46594] = {name = "enchant chest defense"},
    [47051] = {name = "enchant cloak steelweave"},
    [47672] = {name = "enchant cloak mighty armor"},
    [47766] = {name = "enchant chest greater defense"},
    [47898] = {name = "enchant cloak greater speed"},
    [47899] = {name = "enchant cloak wisdom"},
    [47900] = {name = "enchant chest super health"},
    [47901] = {name = "enchant boots tuskarr's vitality"},
    [59619] = {name = "enchant weapon accuracy"},
    [59621] = {name = "enchant weapon berserking"},
    [59625] = {name = "enchant weapon black magic"},
    [59636] = {name = "enchant ring stamina"},
    [60606] = {name = "enchant boots assault"},
    [60609] = {name = "enchant cloak speed"},
    [60616] = {name = "enchant bracers striking"},
    [60619] = {name = "runed titanium rod"},
    [60621] = {name = "enchant weapon greater potency"},
    [60623] = {name = "enchant boots icewalker"},
    [60653] = {name = "enchant shield greater intellect"},
    [60663] = {name = "enchant cloak major agility"},
    [60668] = {name = "enchant gloves crusher"},
    [60691] = {name = "enchant 2h weapon massacre"},
    [60692] = {name = "enchant chest powerful stats"},
    [60707] = {name = "enchant weapon superior potency"},
    [60714] = {name = "enchant weapon mighty spellpower"},
    [60763] = {name = "enchant boots greater assault"},
    [60767] = {name = "enchant bracers superior spellpower"},
    [62256] = {name = "enchant bracers major stamina"},
    [62948] = {name = "enchant staff greater spellpower"},
    [62959] = {name = "enchant staff spellpower"},
    [63746] = {name = "enchant boots lesser accuracy"},
    [64441] = {name = "enchant weapon blade ward"},
    [64579] = {name = "enchant weapon blood draining"},
    [69412] = {name = "abyssal shatter"},
    [71692] = {name = "enchant gloves angler"},    
}